export const REGION_DATA = [
  { city: "서울특별시", district: "송파구", code: "11710" },
  { city: "서울특별시", district: "강동구", code: "11740" },
  { city: "서울특별시", district: "관악구", code: "11620" },
  { city: "서울특별시", district: "서초구", code: "11650" },
  { city: "서울특별시", district: "동작구", code: "11590" },
  { city: "서울특별시", district: "금천구", code: "11545" },
  { city: "서울특별시", district: "영등포구", code: "11560" },
  { city: "서울특별시", district: "강서구", code: "11500" },
  { city: "서울특별시", district: "구로구", code: "11530" },
  { city: "서울특별시", district: "마포구", code: "11440" },
  { city: "서울특별시", district: "양천구", code: "11470" },
  { city: "서울특별시", district: "서대문구", code: "11410" },
  { city: "서울특별시", district: "노원구", code: "11350" },
  { city: "서울특별시", district: "은평구", code: "11380" },
  { city: "서울특별시", district: "강북구", code: "11305" },
  { city: "서울특별시", district: "도봉구", code: "11320" },
  { city: "서울특별시", district: "중랑구", code: "11260" },
  { city: "서울특별시", district: "성북구", code: "11290" },
  { city: "서울특별시", district: "동대문구", code: "11230" },
  { city: "서울특별시", district: "광진구", code: "11215" },
  { city: "서울특별시", district: "성동구", code: "11200" },
  { city: "서울특별시", district: "용산구", code: "11170" },
  { city: "서울특별시", district: "중구", code: "11140" },
  { city: "서울특별시", district: "강남구", code: "11680" },
  { city: "서울특별시", district: "종로구", code: "11110" },
  // { city: "경기도", district: "수원시", code: "41110" },
  { city: "경기도", district: "수원시 영통구", code: "41117" },
  { city: "경기도", district: "수원시 장안구", code: "41111" },
  { city: "경기도", district: "수원시 권선구", code: "41113" },
  { city: "경기도", district: "수원시 팔달구", code: "41115" },
  // { city: "경기도", district: "성남시", code: "41130" },
  { city: "경기도", district: "성남시 수정구", code: "41131" },
  { city: "경기도", district: "성남시 중원구", code: "41133" },
  { city: "경기도", district: "성남시 분당구", code: "41135" },
  { city: "경기도", district: "의정부시", code: "41150" },
  // { city: "경기도", district: "안양시", code: "41170" },
  { city: "경기도", district: "안양시 만안구", code: "41171" },
  { city: "경기도", district: "안양시 동안구", code: "41173" },
  { city: "경기도", district: "광명시", code: "41210" },
  { city: "경기도", district: "평택시", code: "41220" },
  { city: "경기도", district: "하남시", code: "41450" },
  { city: "경기도", district: "동두천시", code: "41250" },
  // { city: "경기도", district: "안산시", code: "41270" },
  { city: "경기도", district: "안산시 상록구", code: "41271" },
  { city: "경기도", district: "안산시 단원구", code: "41273" },
  // { city: "경기도", district: "고양시", code: "41280" },
  { city: "경기도", district: "고양시 덕양구", code: "41281" },
  { city: "경기도", district: "고양시 일산동구", code: "41285" },
  { city: "경기도", district: "고양시 일산서구", code: "41287" },
  { city: "경기도", district: "과천시", code: "41290" },
  { city: "경기도", district: "구리시", code: "41310" },
  { city: "경기도", district: "남양주시", code: "41360" },
  { city: "경기도", district: "오산시", code: "41370" },
  { city: "경기도", district: "시흥시", code: "41390" },
  { city: "경기도", district: "군포시", code: "41410" },
  { city: "경기도", district: "의왕시", code: "41430" },
  // { city: "경기도", district: "용인시", code: "41460" },
  { city: "경기도", district: "용인시 처인구", code: "41461" },
  { city: "경기도", district: "용인시 기흥구", code: "41463" },
  { city: "경기도", district: "용인시 수지구", code: "41465" },
  { city: "경기도", district: "파주시", code: "41480" },
  { city: "경기도", district: "이천시", code: "41500" },
  { city: "경기도", district: "안성시", code: "41550" },
  { city: "경기도", district: "김포시", code: "41570" },
  { city: "경기도", district: "화성시", code: "41590" },
  { city: "경기도", district: "광주시", code: "41610" },
  { city: "경기도", district: "양주시", code: "41630" },
  { city: "경기도", district: "포천시", code: "41650" },
  { city: "경기도", district: "여주시", code: "41670" },
  { city: "경기도", district: "연천군", code: "41800" },
  { city: "경기도", district: "가평군", code: "41820" },
  { city: "경기도", district: "양평군", code: "41830" },
  // { city: "경기도", district: "부천시", code: "41190" },
  { city: "경기도", district: "부천시 오정구", code: "41196" },
  { city: "경기도", district: "부천시 소사구", code: "41194" },
  { city: "경기도", district: "부천시 원미구", code: "41192" },
  { city: "부산광역시", district: "중구", code: "26110" },
  { city: "부산광역시", district: "서구", code: "26140" },
  { city: "부산광역시", district: "동구", code: "26170" },
  { city: "부산광역시", district: "영도구", code: "26200" },
  { city: "부산광역시", district: "부산진구", code: "26230" },
  { city: "부산광역시", district: "동래구", code: "26260" },
  { city: "부산광역시", district: "남구", code: "26290" },
  { city: "부산광역시", district: "북구", code: "26320" },
  { city: "부산광역시", district: "해운대구", code: "26350" },
  { city: "부산광역시", district: "사하구", code: "26380" },
  { city: "부산광역시", district: "금정구", code: "26410" },
  { city: "부산광역시", district: "강서구", code: "26440" },
  { city: "부산광역시", district: "연제구", code: "26470" },
  { city: "부산광역시", district: "수영구", code: "26500" },
  { city: "부산광역시", district: "사상구", code: "26530" },
  { city: "부산광역시", district: "기장군", code: "26710" },
  { city: "대구광역시", district: "남구", code: "27200" },
  { city: "대구광역시", district: "서구", code: "27170" },
  { city: "대구광역시", district: "중구", code: "27110" },
  { city: "대구광역시", district: "동구", code: "27140" },
  { city: "대구광역시", district: "북구", code: "27230" },
  { city: "대구광역시", district: "수성구", code: "27260" },
  { city: "대구광역시", district: "달서구", code: "27290" },
  { city: "대구광역시", district: "달성군", code: "27710" },
  { city: "대구광역시", district: "군위군", code: "27720" },
  { city: "인천광역시", district: "중구", code: "28110" },
  { city: "인천광역시", district: "동구", code: "28140" },
  { city: "인천광역시", district: "미추홀구", code: "28177" },
  { city: "인천광역시", district: "연수구", code: "28185" },
  { city: "인천광역시", district: "남동구", code: "28200" },
  { city: "인천광역시", district: "부평구", code: "28237" },
  { city: "인천광역시", district: "계양구", code: "28245" },
  { city: "인천광역시", district: "서구", code: "28260" },
  { city: "인천광역시", district: "강화군", code: "28710" },
  { city: "인천광역시", district: "옹진군", code: "28720" },
  { city: "광주광역시", district: "동구", code: "29110" },
  { city: "광주광역시", district: "서구", code: "29140" },
  { city: "광주광역시", district: "남구", code: "29155" },
  { city: "광주광역시", district: "북구", code: "29170" },
  { city: "광주광역시", district: "광산구", code: "29200" },
  { city: "대전광역시", district: "동구", code: "30110" },
  { city: "대전광역시", district: "중구", code: "30140" },
  { city: "대전광역시", district: "서구", code: "30170" },
  { city: "대전광역시", district: "유성구", code: "30200" },
  { city: "대전광역시", district: "대덕구", code: "30230" },
  { city: "울산광역시", district: "중구", code: "31110" },
  { city: "울산광역시", district: "남구", code: "31140" },
  { city: "울산광역시", district: "동구", code: "31170" },
  { city: "울산광역시", district: "북구", code: "31200" },
  { city: "울산광역시", district: "울주군", code: "31710" },
  // { city: "경상북도", district: "포항시", code: "47110" },
  { city: "경상북도", district: "포항시 남구", code: "47111" },
  { city: "경상북도", district: "포항시 북구", code: "47113" },
  { city: "경상북도", district: "경주시", code: "47130" },
  { city: "경상북도", district: "김천시", code: "47150" },
  { city: "경상북도", district: "안동시", code: "47170" },
  { city: "경상북도", district: "구미시", code: "47190" },
  { city: "경상북도", district: "영주시", code: "47210" },
  { city: "경상북도", district: "영천시", code: "47230" },
  { city: "경상북도", district: "상주시", code: "47250" },
  { city: "경상북도", district: "문경시", code: "47280" },
  { city: "경상북도", district: "경산시", code: "47290" },
  { city: "경상북도", district: "의성군", code: "47730" },
  { city: "경상북도", district: "청송군", code: "47750" },
  { city: "경상북도", district: "영양군", code: "47760" },
  { city: "경상북도", district: "영덕군", code: "47770" },
  { city: "경상북도", district: "청도군", code: "47820" },
  { city: "경상북도", district: "고령군", code: "47830" },
  { city: "경상북도", district: "성주군", code: "47840" },
  { city: "경상북도", district: "칠곡군", code: "47850" },
  { city: "경상북도", district: "예천군", code: "47900" },
  { city: "경상북도", district: "봉화군", code: "47920" },
  { city: "경상북도", district: "울진군", code: "47930" },
  { city: "경상북도", district: "울릉군", code: "47940" },
  // { city: "경상남도", district: "창원시", code: "48120" },
  { city: "경상남도", district: "창원시 의창구", code: "48121" },
  { city: "경상남도", district: "창원시 성산구", code: "48123" },
  { city: "경상남도", district: "창원시 마산합포구", code: "48125" },
  { city: "경상남도", district: "창원시 마산회원구", code: "48127" },
  { city: "경상남도", district: "창원시 진해구", code: "48129" },
  { city: "경상남도", district: "사천시", code: "48240" },
  { city: "경상남도", district: "진주시", code: "48170" },
  { city: "경상남도", district: "통영시", code: "48220" },
  { city: "경상남도", district: "창녕군", code: "48740" },
  { city: "경상남도", district: "김해시", code: "48250" },
  { city: "경상남도", district: "밀양시", code: "48270" },
  { city: "경상남도", district: "거제시", code: "48310" },
  { city: "경상남도", district: "양산시", code: "48330" },
  { city: "경상남도", district: "의령군", code: "48720" },
  { city: "경상남도", district: "함안군", code: "48730" },
  { city: "경상남도", district: "고성군", code: "48820" },
  { city: "경상남도", district: "남해군", code: "48840" },
  { city: "경상남도", district: "하동군", code: "48850" },
  { city: "경상남도", district: "산청군", code: "48860" },
  { city: "경상남도", district: "함양군", code: "48870" },
  { city: "경상남도", district: "거창군", code: "48880" },
  { city: "경상남도", district: "합천군", code: "48890" },
  { city: "전라남도", district: "목포시", code: "46110" },
  { city: "전라남도", district: "여수시", code: "46130" },
  { city: "전라남도", district: "순천시", code: "46150" },
  { city: "전라남도", district: "나주시", code: "46170" },
  { city: "전라남도", district: "광양시", code: "46230" },
  { city: "전라남도", district: "담양군", code: "46710" },
  { city: "전라남도", district: "곡성군", code: "46720" },
  { city: "전라남도", district: "구례군", code: "46730" },
  { city: "전라남도", district: "고흥군", code: "46770" },
  { city: "전라남도", district: "보성군", code: "46780" },
  { city: "전라남도", district: "화순군", code: "46790" },
  { city: "전라남도", district: "장흥군", code: "46800" },
  { city: "전라남도", district: "강진군", code: "46810" },
  { city: "전라남도", district: "해남군", code: "46820" },
  { city: "전라남도", district: "영암군", code: "46830" },
  { city: "전라남도", district: "무안군", code: "46840" },
  { city: "전라남도", district: "함평군", code: "46860" },
  { city: "전라남도", district: "영광군", code: "46870" },
  { city: "전라남도", district: "장성군", code: "46880" },
  { city: "전라남도", district: "완도군", code: "46890" },
  { city: "전라남도", district: "진도군", code: "46900" },
  { city: "전라남도", district: "신안군", code: "46910" },
  // { city: "충청북도", district: "청주시", code: "43110" },
  { city: "충청북도", district: "청주시 상당구", code: "43111" },
  { city: "충청북도", district: "청주시 서원구", code: "43112" },
  { city: "충청북도", district: "청주시 흥덕구", code: "43113" },
  { city: "충청북도", district: "청주시 청원구", code: "43114" },
  { city: "충청북도", district: "충주시", code: "43130" },
  { city: "충청북도", district: "제천시", code: "43150" },
  { city: "충청북도", district: "보은군", code: "43720" },
  { city: "충청북도", district: "옥천군", code: "43730" },
  { city: "충청북도", district: "영동군", code: "43740" },
  { city: "충청북도", district: "증평군", code: "43745" },
  { city: "충청북도", district: "진천군", code: "43750" },
  { city: "충청북도", district: "괴산군", code: "43760" },
  { city: "충청북도", district: "음성군", code: "43770" },
  { city: "충청북도", district: "단양군", code: "43800" },
  // { city: "충청남도", district: "천안시", code: "44130" },
  { city: "충청남도", district: "천안시 동남구", code: "44131" },
  { city: "충청남도", district: "천안시 서북구", code: "44133" },
  { city: "충청남도", district: "공주시", code: "44150" },
  { city: "충청남도", district: "보령시", code: "44180" },
  { city: "충청남도", district: "아산시", code: "44200" },
  { city: "충청남도", district: "서산시", code: "44210" },
  { city: "충청남도", district: "논산시", code: "44230" },
  { city: "충청남도", district: "계룡시", code: "44250" },
  { city: "충청남도", district: "당진시", code: "44270" },
  { city: "충청남도", district: "금산군", code: "44710" },
  { city: "충청남도", district: "부여군", code: "44760" },
  { city: "충청남도", district: "서천군", code: "44770" },
  { city: "충청남도", district: "청양군", code: "44790" },
  { city: "충청남도", district: "홍성군", code: "44800" },
  { city: "충청남도", district: "예산군", code: "44810" },
  { city: "충청남도", district: "태안군", code: "44825" },
  // { city: "세종특별자치시", district: "세종특별자치시", code: "36110" },
  { city: "세종특별자치시", district: "", code: "36110" },
  { city: "전북특별자치도", district: "부안군", code: "52800" },
  { city: "전북특별자치도", district: "고창군", code: "52790" },
  { city: "전북특별자치도", district: "순창군", code: "52770" },
  { city: "전북특별자치도", district: "임실군", code: "52750" },
  { city: "전북특별자치도", district: "장수군", code: "52740" },
  { city: "전북특별자치도", district: "무주군", code: "52730" },
  { city: "전북특별자치도", district: "진안군", code: "52720" },
  { city: "전북특별자치도", district: "완주군", code: "52710" },
  { city: "전북특별자치도", district: "김제시", code: "52210" },
  { city: "전북특별자치도", district: "남원시", code: "52190" },
  { city: "전북특별자치도", district: "정읍시", code: "52180" },
  { city: "전북특별자치도", district: "익산시", code: "52140" },
  { city: "전북특별자치도", district: "군산시", code: "52130" },
  // { city: "전북특별자치도", district: "전주시", code: "52110" },
  { city: "전북특별자치도", district: "전주시 덕진구", code: "52113" },
  { city: "전북특별자치도", district: "전주시 완산구", code: "52111" },
  { city: "제주특별자치도", district: "제주시", code: "50110" },
  { city: "제주특별자치도", district: "서귀포시", code: "50130" },
  { city: "강원특별자치도", district: "양양군", code: "51830" },
  { city: "강원특별자치도", district: "고성군", code: "51820" },
  { city: "강원특별자치도", district: "인제군", code: "51810" },
  { city: "강원특별자치도", district: "화천군", code: "51790" },
  { city: "강원특별자치도", district: "양구군", code: "51800" },
  { city: "강원특별자치도", district: "철원군", code: "51780" },
  { city: "강원특별자치도", district: "정선군", code: "51770" },
  { city: "강원특별자치도", district: "평창군", code: "51760" },
  { city: "강원특별자치도", district: "영월군", code: "51750" },
  { city: "강원특별자치도", district: "횡성군", code: "51730" },
  { city: "강원특별자치도", district: "홍천군", code: "51720" },
  { city: "강원특별자치도", district: "속초시", code: "51210" },
  { city: "강원특별자치도", district: "삼척시", code: "51230" },
  { city: "강원특별자치도", district: "태백시", code: "51190" },
  { city: "강원특별자치도", district: "동해시", code: "51170" },
  { city: "강원특별자치도", district: "강릉시", code: "51150" },
  { city: "강원특별자치도", district: "원주시", code: "51130" },
  { city: "강원특별자치도", district: "춘천시", code: "51110" },
];

export const CITIES = [
  "서울특별시",
  "경기도",
  "부산광역시",
  "대구광역시",
  "인천광역시",
  "광주광역시",
  "대전광역시",
  "울산광역시",
  "경상북도",
  "경상남도",
  "전라남도",
  "충청북도",
  "충청남도",
  "세종특별자치시",
  "전북특별자치도",
  "제주특별자치도",
  "강원특별자치도",
];
